f=open("testfile.txt","a")
f.write("/n this is my append to my test file")
f.close()
f=open("testfile.txt","r")
print(f.read())
f.close()
f=open("testfile.txt","a+")
f.write("/n babe wassaupp")
print(f.read())
f.seek(0,0)
print(f.read())